export const testLocations: any = [
  {
    name: 'Eiffel Tower start',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'The Eiffel Tower is an iconic iron lattice structure located in Paris, France, known for its towering height and distinctive silhouette. Built in 1889, it serves as a symbol of French engineering prowess and attracts millions of visitors annually with its panoramic views of the city.',
    descriptionLong:`The Eiffel Tower stands tall and proud as an architectural marvel in the heart of Paris, France. Designed by Gustave Eiffel, this iconic iron lattice structure has become an enduring symbol of the city and a testament to human ingenuity. Standing at a towering height of 330 meters (1,083 feet), the Eiffel Tower held the title of the tallest man-made structure in the world for over 40 years. Constructed between 1887 and 1889, the tower was initially met with mixed reactions from the public. However, it quickly captured the imagination of people worldwide and became a beloved landmark. Composed of intricate wrought-iron latticework, the Eiffel Tower boasts an open framework that allows visitors to appreciate the grandeur of its design while providing breathtaking views of the surrounding cityscape  .Ascending the tower is an experience in itself. Visitors can choose between taking the stairs or elevators to reach the different levels, each offering unique vantage points. The first two levels house restaurants, shops, and exhibits that delve into the tower's history, while the summit provides panoramic views of Paris, with notable landmarks like the Seine River, Notre-Dame Cathedral, and the Arc de Triomphe visible from above. As a cultural icon, the Eiffel Tower has been featured in countless films, artworks, and photographs, further cementing its status as a global symbol of romance, elegance, and architectural brilliance. Its allure draws millions of tourists each year, all eager to marvel at its beauty and capture a piece of its timeless splendor.`,
    lat: '48.8584',
    lng: '2.2945',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: null,
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descriptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '49.1231',
    lng: '3.2321',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '6.9',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descriptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.0001',
    lng: '2.3321',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '4.2',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descriptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.8738',
    lng: '2.2950',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descriptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.8338',
    lng: '2.3324',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },

  {
    name: 'Louve',
    address: '321 somewhere in Paris',
    rating: '4.5',
    reviewCount: '123',
    descriptionShort: 'Art Art Art',
    lat: '48.8606',
    lng: '2.3376',
    attractionType: 'Museum',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'NotreDam',
    address: '456 Somewhere in paris',
    rating: '2',
    reviewCount: '123',
    descriptionShort: 'Big building',
    lat: '48.852966',
    lng: '2.349902',
    attractionType: 'Building',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
]

export const testTrips = {
  Paris: [
    {
      name: 'Eiffel Tower',
      address: '123 somewhere in Paris',
      rating: '4',
      reviewCount: '123',
      descriptionShort: 'Could be bigger',
      descritptionLong:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      lat: '1.232',
      lng: '1.232',
      attractionType: 'Tourist',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
    {
      name: 'Eiffel Tower',
      address: '123 somewhere in Paris',
      rating: '4',
      reviewCount: '123',
      descriptionShort: 'Could be bigger',
      descritptionLong:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      lat: '1.232',
      lng: '1.232',
      attractionType: 'Tourist',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
    {
      name: 'Eiffel Tower',
      address: '123 somewhere in Paris',
      rating: '4',
      reviewCount: '123',
      descriptionShort: 'Could be bigger',
      descritptionLong:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      lat: '1.232',
      lng: '1.232',
      attractionType: 'Tourist',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
    {
      name: 'Eiffel Tower',
      address: '123 somewhere in Paris',
      rating: '4',
      reviewCount: '123',
      descriptionShort: 'Could be bigger',
      descritptionLong:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      lat: '1.232',
      lng: '1.232',
      attractionType: 'Tourist',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
    {
      name: 'Eiffel Tower',
      address: '123 somewhere in Paris',
      rating: '4',
      reviewCount: '123',
      descriptionShort: 'Could be bigger',
      descritptionLong:
        'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
      lat: '1.232',
      lng: '1.232',
      attractionType: 'Tourist',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },

    {
      name: 'Louve',
      address: '321 somewhere in Paris',
      rating: '4.5',
      reviewCount: '123',
      description: 'Art Art Art',
      lat: '2.123',
      lng: '2.123',
      attractionType: 'Museum',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
    {
      name: 'NotreDam',
      address: '456 Somewhere in paris',
      rating: '2',
      reviewCount: '123',
      description: 'Big building',
      lat: '4.32',
      lng: '4.34',
      attractionType: 'Building',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
  ],
  abcdefghijklmno: [
    {
      name: 'BrandenBurg Gate',
      address: '123 berlin',
      rating: '4',
      reviewCount: '34',
      description: 'A gate',
      lat: '4.44',
      lng: '5.55',
      attractionType: 'Gate',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
    {
      name: 'Video Game Museum',
      address: '123 pewpew Dr',
      rating: '5',
      reviewCount: '420',
      description: 'Cool videogames',
      lat: '4.20',
      lng: '6.9',
      attractionType: 'Museum',
      imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
    },
  ],
  another: [],
  another1: [],
  another2: [],
  another3: [],
  another4: [],
  another5: [],
  another6: [],
}
