export const testLocations: any = [
  {
    name: 'Eiffel Tower start',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descritptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.8584',
    lng: '2.2945',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descritptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '49.1231',
    lng: '3.2321',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descritptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.0001',
    lng: '2.3321',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descritptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.8738',
    lng: '2.2950',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'Eiffel Tower',
    address: '123 somewhere in Paris',
    rating: '4',
    reviewCount: '123',
    descriptionShort: 'Could be bigger',
    descritptionLong:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
    lat: '48.8338',
    lng: '2.3324',
    attractionType: 'Tourist',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },

  {
    name: 'Louve',
    address: '321 somewhere in Paris',
    rating: '4.5',
    reviewCount: '123',
    description: 'Art Art Art',
    lat: '48.8606',
    lng: '2.3376',
    attractionType: 'Museum',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
  {
    name: 'NotreDam',
    address: '456 Somewhere in paris',
    rating: '2',
    reviewCount: '123',
    description: 'Big building',
    lat: '48.852966',
    lng: '2.349902',
    attractionType: 'Building',
    imageUrl: 'https://lh5.googleusercontent.com/p/AF1QipOnJHzIOu1VUvkTX0GKjmqK-NdgXWJEUa8m2YPd=s549-k-no',
  },
]
