import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import NavBar from '@/components/NavBar'
import { use, useMemo } from 'react'
import {GoogleMap, useLoadScript, Marker, useJsApiLoader} from '@react-google-maps/api'
import { env } from 'process'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const key: any = process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
  const { isLoaded } = useLoadScript({
    'googleMapsApiKey': key
  })
  if(!isLoaded) return <div>Loading...</div>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <NavBar />
      <Map />
      </main>
    </>
  )
}

function Map(){
  return <GoogleMap zoom={10} center={{lat:51, lng:0 }} mapContainerClassName='map-container'></GoogleMap>
}
